# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\allis\OneDrive\Documents\WIT Year 2\Network Programming\NetworkProject\NetworkProgramming.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 760)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        # ----- MAIN LAYOUT (LEFT / RIGHT) -----
        main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        main_layout.setObjectName("main_layout")

        # ================= LEFT SIDE (SEND MAIL) =================
        left_layout = QtWidgets.QVBoxLayout()
        left_layout.setObjectName("left_layout")

        # Title label
        self.labelintro = QtWidgets.QLabel(self.centralwidget)
        self.labelintro.setObjectName("labelintro")
        left_layout.addWidget(self.labelintro)

        # User / SendTo row (form style)
        form_layout = QtWidgets.QFormLayout()
        form_layout.setObjectName("form_layout")

        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setObjectName("user_label")
        self.sendtoEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sendtoEdit.setObjectName("sendtoEdit")

        form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_label)
        form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sendtoEdit)

        left_layout.addLayout(form_layout)

        # Message label + editor
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        left_layout.addWidget(self.label_4)

        self.user_message = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.user_message.setObjectName("user_message")
        left_layout.addWidget(self.user_message)

        # Buttons row (Send / Logout) aligned right
        button_row = QtWidgets.QHBoxLayout()
        button_row.addStretch()

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        button_row.addWidget(self.pushButton)

        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setObjectName("logout_button")
        button_row.addWidget(self.logout_button)

        left_layout.addLayout(button_row)

        # ================= RIGHT SIDE (INBOX / GRAPHICS) =================
        right_layout = QtWidgets.QVBoxLayout()
        right_layout.setObjectName("right_layout")

        # Inbox header: label + Refresh button
        header_layout = QtWidgets.QHBoxLayout()
        header_layout.setObjectName("header_layout")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        header_layout.addWidget(self.label_2)

        header_layout.addStretch()

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        header_layout.addWidget(self.pushButton_2)

        right_layout.addLayout(header_layout)

        # Scroll area (inbox)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        right_layout.addWidget(self.scrollArea)

        # Graphics view below inbox
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        right_layout.addWidget(self.graphicsView)

        # Add left and right layouts to main layout
        main_layout.addLayout(left_layout, 1)
        main_layout.addLayout(right_layout, 1)

        # ----- MENUBAR / STATUSBAR -----
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 25))
        self.menubar.setObjectName("menubar")
        self.menuEmail_Client = QtWidgets.QMenu(self.menubar)
        self.menuEmail_Client.setObjectName("menuEmail_Client")
        self.menubar.addAction(self.menuEmail_Client.menuAction())
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.labelintro.setText(_translate("MainWindow", "Send Mail"))
        self.label_2.setText(_translate("MainWindow", "Inbox"))
        self.user_label.setText(_translate("MainWindow", "User"))
        self.label_4.setText(_translate("MainWindow", "Message"))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh"))
        self.menuEmail_Client.setTitle(_translate("MainWindow", "Email Client"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
