# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\allis\OneDrive\Documents\WIT Year 2\Network Programming\NetworkProject\NetworkProgramming.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_message = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.user_message.setGeometry(QtCore.QRect(10, 170, 421, 371))
        self.user_message.setObjectName("user_message")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 570, 90, 29))
        self.pushButton.setObjectName("pushButton")
        self.sendtoEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sendtoEdit.setGeometry(QtCore.QRect(10, 90, 291, 28))
        self.sendtoEdit.setObjectName("sendtoEdit")
        self.labelintro = QtWidgets.QLabel(self.centralwidget)
        self.labelintro.setGeometry(QtCore.QRect(20, 10, 111, 20))
        self.labelintro.setObjectName("labelintro")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 0, 63, 20))
        self.label_2.setObjectName("label_2")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(10, 60, 63, 20))
        self.user_label.setObjectName("user_label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 63, 20))
        self.label_4.setObjectName("label_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(500, 90, 361, 71))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(860, 90, 20, 71))
       # self.verticalScrollBar.setOrientation(QtCore.Qt.Qt::Orientation::Vertical) not in use until display of messages is fixed
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(500, 170, 361, 371))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 50, 90, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 25))
        self.menubar.setObjectName("menubar")
        self.menuEmail_Client = QtWidgets.QMenu(self.menubar)
        self.menuEmail_Client.setObjectName("menuEmail_Client")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuEmail_Client.menuAction())
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(500, 570, 90, 29))
        self.logout_button.setObjectName("logout_button")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.labelintro.setText(_translate("MainWindow", "Send Mail"))
        self.label_2.setText(_translate("MainWindow", "Inbox"))
        self.user_label.setText(_translate("MainWindow", "User"))
        self.label_4.setText(_translate("MainWindow", "Message"))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh"))
        self.menuEmail_Client.setTitle(_translate("MainWindow", "Email Client"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
