# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(683, 482)

        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        loginWindow.setCentralWidget(self.centralwidget)

        # ---- MAIN VERTICAL LAYOUT FOR WHOLE WINDOW ----
        main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        main_layout.setContentsMargins(40, 40, 40, 40)
        main_layout.setSpacing(20)

        # Welcome label centered at top
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(self.welcomeLabel)

        # ---- FORM AREA (USERNAME ONLY) ----
        form_layout = QtWidgets.QFormLayout()
        form_layout.setLabelAlignment(QtCore.Qt.AlignLeft)
        form_layout.setFormAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        form_layout.setHorizontalSpacing(20)
        form_layout.setVerticalSpacing(10)

        # Username
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setObjectName("usernameEdit")
        form_layout.addRow(self.label, self.usernameEdit)

        main_layout.addLayout(form_layout)

        # ---- TERMS CHECKBOX ----
        self.termsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.termsCheck.setObjectName("termsCheck")
        main_layout.addWidget(self.termsCheck)

        # Take remaining vertical space before button
        main_layout.addStretch()

        # ---- LOGIN BUTTON ----
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.loginButton.setMinimumHeight(32)
        main_layout.addWidget(self.loginButton)

        # ---- STATUS BAR / ACTION ----
        self.statusbar = QtWidgets.QStatusBar(loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)

        self.actionLogin = QtWidgets.QAction(loginWindow)
        self.actionLogin.setObjectName("actionLogin")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Chat Login"))
        self.label.setText(_translate("loginWindow", "Username"))
        self.loginButton.setText(_translate("loginWindow", "Start Chat"))
        self.termsCheck.setText(
            _translate(
                "loginWindow",
                "I agree to the terms and conditions of the chat",
            )
        )
        self.welcomeLabel.setText(_translate("loginWindow", "Welcome to the Chat"))
        self.actionLogin.setText(_translate("loginWindow", "Login"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QMainWindow()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec_())
