# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(683, 482)
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 100, 331, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.usernameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usernameEdit.setObjectName("usernameEdit")
        self.verticalLayout.addWidget(self.usernameEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ipEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ipEdit.setObjectName("ipEdit")
        self.verticalLayout.addWidget(self.ipEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.portNum = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.portNum.setObjectName("portNum")
        self.verticalLayout.addWidget(self.portNum)
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(200, 380, 299, 29))
        self.loginButton.setObjectName("loginButton")
        self.termsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.termsCheck.setGeometry(QtCore.QRect(190, 330, 341, 21))
        self.termsCheck.setObjectName("termsCheck")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(290, 50, 151, 20))
        self.welcomeLabel.setObjectName("welcomeLabel")
        loginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(loginWindow)
        self.actionLogin.setObjectName("actionLogin")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "loginWindow"))
        self.label.setText(_translate("loginWindow", "Username"))
        self.label_2.setText(_translate("loginWindow", "IP Address"))
        self.label_3.setText(_translate("loginWindow", "Port (optional)"))
        self.loginButton.setText(_translate("loginWindow", "Start Chat"))
        self.termsCheck.setText(_translate("loginWindow", "I agree to the terms and conditions of the chat"))
        self.welcomeLabel.setText(_translate("loginWindow", "Welcome to the Chat"))
        self.actionLogin.setText(_translate("loginWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QMainWindow()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec_())
